# -*- coding: utf-8 -*-
"""chroma_setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxcjXk5-uXpsyNrvzVltqBjikuDmJaFI
"""

import sys
import pysqlite3

sys.modules["sqlite3"] = pysqlite3
sys.modules["pysqlite3"] = pysqlite3

# chroma_setup.py
#left off here---- use the new repo and file name, then try to load the collection again.
#once the collection loads, you should be able to call on it from the app.py
#there is a chance that the code to upload the zip from the original worksheet didn't work properly. If thats the case, upload the zip manually to huggingface from your files

import zipfile
import tempfile
from huggingface_hub import hf_hub_download
import chromadb

def load_chroma_collection():
    # Step 1: Download the zip from Hugging Face Dataset Hub
    zip_path = hf_hub_download(
        repo_id="pqhunter15/chromadb-support-db_2",       # Replace with your repo
        filename="chromadb_collection2.zip",                # Replace with your file
        repo_type="dataset"
    )

    # Step 2: Extract it to a temporary directory
    extract_dir = tempfile.mkdtemp()
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_dir)

    # Step 3: Initialize ChromaDB client from the extracted path
    client = chromadb.PersistentClient(path=extract_dir)

    # Step 4: Load the collection
    collection = client.get_collection("support_collection_1")     # Replace with your collection name
    return collection
    
collection = load_chroma_collection()
print("Done. Current count:", collection.count())
