[theme]
base = "dark"
primaryColor = "#32CD32"             # Lime green
backgroundColor = "#121212"          # Dark gray background
secondaryBackgroundColor = "#1E1E1E" # For input panels and cards
textColor = "#E0E0E0"                # Soft white
font = "sans serif"
